version: '3.8'

services:
  postgres:
    container_name: postgres-diffuser
    image: postgres:14.4
    ports:
      - '5555:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: diffuser-api
      POSTGRES_PASSWORD: 12121212
      POSTGRES_DB: diffuser-db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672 # AMQP protocol port
      - 15672:15672 # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=12121212
    restart: unless-stopped

volumes:
  postgres_data:
  rabbitmq_data:
  rabbitmq_logs:
