version: '3.8'

services:
  postgres:
    container_name: postgres-diffuser
    image: postgres:14.4
    ports:
      - '5555:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: diffuser-api
      POSTGRES_PASSWORD: 12121212
      POSTGRES_DB: diffuser-db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672 # AMQP protocol port
      - 15672:15672 # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=12121212
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2024-07-04T14-25-45Z-cpuv1
    volumes:
      - minio_data:/data
    ports:
      - '10000:9000'
      - '10001:9001'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: minio server /data/minio/ --console-address ":9001"

  nginx:
    container_name: diffuser-nginx
    image: nginx:1.15-alpine
    depends_on:
      - postgres
      - minio
      - rabbitmq
    volumes:
      - ./nginx_dev:/etc/nginx/conf.d
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    ports:
      - '8080:8080'

volumes:
  postgres_data:
  rabbitmq_data:
  rabbitmq_logs:
  minio_data:
